.circleci/config.yml
docs/getting_started.rst
docs/index.rst
hiplot/__init__.py
hiplot/experiment.py
hiplot/fetchers.py
hiplot/render.py
hiplot/test_experiment.py
hiplot/test_fetchers.py
src/parallel.tsx
src/tutorial/tutorial.css
src/tutorial/tutorial.tsx

- Parameters in URL overwrite parameters in experiment

WIP for version 0.1.2

---

hiplot/__init__.py
hiplot/experiment.py
hiplot/fetchers.py
hiplot/ipython.py
hiplot/test_experiment.py
src/infertypes.ts
src/plotxy.tsx
src/types.ts

- Enable scrolling on jupyter iframe
- Possible to enforce minimum/maximum values for the axis
- PlotXY: Space X ticks more

WIP for version 0.1.3

---

.circleci/config.yml
MANIFEST.in
README.md
docs/getting_started.rst
hiplot/__init__.py
src/controls.tsx

- Test wheel/package in CircleCI
- Add credits to README
- The export button will download data as a CSV directly (instead of opening a new window)

WIP version 0.1.4

---

MANIFEST.in
hiplot/__init__.py
setup.py

Add (again) missing files in the tar

HiPlot 0.1.7

---

.circleci/config.yml
MANIFEST.in
hiplot/__init__.py
setup.py

- Add testing for HTML generation from wheel/sdist

HiPlot 0.1.7.post1

---

hiplot/experiment.py
hiplot/test_experiment.py
requirements/dev.txt

tested with `pytest hiplot/test_experiment.py -k "test_from_dataframe"`

Add Experiment.from_dataframe()

---

hiplot/experiment.py
hiplot/fetchers_demo.py
src/hiplot.tsx
src/infertypes.ts
src/lib/d3_scales.ts
src/types.ts

Add support for timestamps variable type

---

hiplot/__init__.py

Main changes:
- Implement new variable type: Timestamp
- Implement API to retrieve brush extents in client side
- Embed in notebooks directly instead of wrapping in an iframe
- Misc bug fixes (#50, #51)

Bump to version 0.1.8

---

docs/py_reference.rst
hiplot/experiment.py
hiplot/fetchers_demo.py
hiplot/test_experiment.py
src/elements.tsx
src/hiplot.tsx
src/infertypes.ts
src/parallel/parallel.tsx
src/types.ts

Possible to set colormap for columns

---

hiplot/__init__.py

New features:
- Possible to use a custom colormap
- Data filters applied are now stored in the URL (allows to restore it on `refresh`, or to share it with the URL)

HiPlot version 0.1.9

---

.circleci/config.yml
docs/conf.py
hiplot/__init__.py
setup.py

Adds a new package for hiplot nightly builds

HiPlot nightly builds

---

hiplot/experiment.py
hiplot/fetchers_demo.py
src/hiplot.css
src/infertypes.ts
src/lib/svghelpers.ts
src/parallel/parallel.tsx
src/plotxy.tsx
src/rowsdisplaytable.tsx
src/types.ts
webpack.config.js

Add feature to change axis color/styling

---

src/hiplot.css
src/lib/svghelpers.ts
src/parallel/parallel.tsx

Tooltip on column axis

---

src/infertypes.ts
src/parallel/parallel.tsx

Possible to restore axis in parallel plot

---

src/distribution/plot.tsx
src/hiplot.css
src/lib/resizable.tsx
src/lib/svghelpers.ts
src/plotxy.tsx

Distribution: Add ticks grid to graph

---

.circleci/test_e2e.py
src/hiplot.tsx
src/hiplot_test.tsx
src/lib/d3_scales.ts
src/parallel/parallel.tsx
src/plugin.ts

Improve slicing & harder e2e testing (fixes bool/percentile cases)

---

examples/javascript/package-lock.json
examples/javascript/package.json
examples/javascript/src/index.js
src/component.tsx
src/hiplot_streamlit.tsx
src/plotxy.tsx

Simplify how we can register callbacks

Example to retrieve selected uids

---

.circleci/test_notebook.py
hiplot/ipython.py

Fix Jupyter Notebook + Stricter CI

---

package.json
src/hiplot.scss
src/lib/svghelpers.ts
webpack.config.js

Fix axis names rendering on webkit based browsers (safari)

---

README.md

Citing hiplot

---

NOTICE
examples/javascript/package-lock.json
hiplot/fetchers.py
package-lock.json
requirements/dev.txt
src/streamlit/StreamlitReact.tsx
src/streamlit/index.tsx
src/streamlit/streamlit.ts

Also fix CI tests which broke in-between

Add NOTICE, fix copyright and npm audit

---

hiplot/fetchers_demo.py
src/hiplot.scss
src/lib/svghelpers.ts
src/parallel/parallel.tsx
src/plotxy.tsx

Columns with long names with spaces

---

hiplot/fetchers_demo.py
src/infertypes.ts
src/parallel/parallel.tsx

[parallel plot] Dont hide columns with force_value_min/force_value_max

---

README.md

Thanks for the great library, I added a working Colab example and badges to make it easier for new users (and myself, sometimes)
Hope to contribute some more code if possible!

Added notebook examples

---

README.md

Pinging @GoldenCorgi and @callistachang for visibility - thank you for your contributions 🥇

Add contributors list to README.md

---

README.md

added a few more badges and a link to the examples page, I'm adding in a few more examples using Optuna & LightGBM/Pytorch

Update README with a few more badges

---

webpack.config.js

Re-enable AMD parser

---

hiplot/experiment.py
hiplot/fetchers_demo.py
src/infertypes.ts

Inverse colormap

---

hiplot/experiment.py
hiplot/render.py

**TEST PLAN**
Currently being tested in #13 
Closes #13

Fix encoding in hiplot-render for windows users

---

src/distribution/plugin.tsx
src/hiplot_streamlit.tsx
src/parallel/parallel.tsx
src/plotxy.tsx

Streamlit: Dont forget to change streamlit height when resizing plugins

---

.circleci/config.yml
hiplot/experiment.py
hiplot/fetchers_demo.py
src/component.tsx
src/types.ts

Make it possible to reorder or disable plugins

---

hiplot/fetchers_demo.py
src/infertypes.ts
src/lib/d3_scales.ts

Fix selecting range for numeric scale with outliers

---

README.md
docs/index.rst

Our mission at [Meta Open Source](https://opensource.facebook.com/) is to empower communities through open source, and we believe that it means building a welcoming and safe environment for all. As a part of this work, we are adding this banner in support for Ukraine during this crisis.

docs: add GH button in support of Ukraine 

---

src/parallel/parallel.tsx

Fix column ordering after resize

---

hiplot/streamlit_helpers.py

Replace deprecated streamlit api method
